version: 2.1

jobs:
  travail:
    working_directory: ~/project/wksp
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      - run: ls -al
      - persist_to_workspace:
          root: ~/project/wksp
          paths:
            - myfile.txt
      
  leworkspace:
    working_directory: ~/project/wksp
    docker:
      - image: cimg/node:10.24.0
    steps:
      - run: ls -al
      - checkout
      - attach_workspace:
          at: ~/project/wksp
      - run: ls -al
                   
workflows:

  whodidthis:
    jobs:
      - travail
      - leworkspace:
          requires:
            - travail
