version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - setup_remote_docker:
           version: 20.10.7

      - run: |
          ssh remote-docker \ ssh -V
      - run: |
          ssh remote-docker \ echo "Public IP is now $(curl checkip.amazonaws.com)"
          
workflows:
  build-deploy:
    jobs:
      - setup
