version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:2020.08

jobs:
  build:
    executor: main
    steps:
      - run: |
          ssh -V
      - checkout

workflows:
  workflow1:
    jobs:
      - build
