version: 2.1

jobs:
  travail:
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      
      - run: |
          ls -al wksp
          pwd
          echo "toto" > ~/project/wksp/myfile.txt
      - persist_to_workspace:
          root: ~/project/wksp
          paths:
            - myfile.txt
      
  leworkspace:
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      - run: |
          cd wksp
          pwd
          ls -alt --time-style=full-iso
          cat myfile.txt
          sleep 5
      - attach_workspace:
          at: ~/project/wksp
      - run: |
          pwd
          cat myfile.txt
                   
workflows:

  whodidthis:
    jobs:
      - travail
      - leworkspace:
          requires:
            - travail
