version: 2.1
  
jobs:
  setup:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Docker version
          command: |
            docker --version
      - run: echo "toto" > /tmp/file.txt
      - run: docker build . /tmp
      
          
workflows:
  build-deploy:
    jobs:
      - setup
