version: 2.1
    
jobs:
  setup:
    docker:
      - image: circleci/ruby:2.6.8-node-browsers
    steps:
      - run: |
          circleci tests split --help
          
# Comment here 😃           
                
workflows:
  build-deploy:
    jobs:
      - setup
