version: 2.1

jobs:
  build:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
    parallelism: 2

    steps:
      - checkout
      - run:
          command: |
            echo "Hello"
            go list ./... | CIRCLE_INTERNAL_TASK_DATA="C:${CIRCLE_INTERNAL_TASK_DATA}" circleci tests split --split-by=timings
      - store_test_results:
          path: results

workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
