version: 2.1

orbs:
  slack: circleci/slack@4.12.1
  
jobs:
  setup:
    docker:
      - image: node:12.16.1
    steps:
              
      - run:
          name: Check curl version
          command: |
              curl --version
#       - run:
#           name: Upgrade curl
#           command: |
#               add-apt-repository ppa:savoury1/curl34 -y
#               apt update && apt install curl -y

#       - run:
#           name: Check curl version again
#           command: |
#               curl --version

#       - run: |     
#           #echo \'export BLA=\'$(cat notif.txt| awk '{printf "%s\\n", $0}' | sed 's/\"/\\"/g') \'\' >> $BASH_ENV
#           cat notif.txt|sed ':a;N;$!ba;s/\n/\\n/g'|sed 's/\"/\\"/g' > message.txt
#           #cat notif.txt|awk '{printf "%s\\n", $0}'|sed 's/\"/\\"/g' > message.txt
          
#           #cat notif.txt | sed 's/\"/\\"/g' > message.txt ####  Doesn't work > parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 13, column 41
          
#           #cat notif.txt|awk '{printf "%s\\n", $0}' > message.txt ####  Doesn't work > parse error: Invalid numeric literal at line 7, column 183

#           echo 'export MESSAGE="*Our Changes to be applied from terraform:* \`\`\`$(cat message.txt)\`\`\`" ' >> $BASH_ENV
#           #echo 'export "GOOD_MESS=$(echo \"$MESSAGE\" | awk \'{printf "%s\\n", $0}\'|sed \'s/\"/\\"/g\')'
#           source $BASH_ENV
#           #echo $BLA
#           echo $MESSAGE
          
      - slack/notify:
                custom: |
                  {
                    "text": "",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}` , $COMMITTER_NAME_VAR , $COMMITTER_NAME , ${LE_COMMIT} executed by `${CIRCLE_USERNAME}`"
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Job"
                            },
                            "url": "${CIRCLE_BUILD_URL}"
                          }
                        ]
                      }
                    ]
                  }
                event: always
              
          
workflows:
  build-deploy:
#     when:
#       equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - setup
