version: 2.1

jobs:
  show-glob:
    docker:
      - image: notion/circleci:0.135
    resource_class: small
    steps:
      - run: shopt globstar

      - run:
          command: |
            shopt -s globstar
            shopt globstar
          when: always

      - run:
          command: shopt globstar
          when: always

workflows:
  La-Build:
    jobs:
    - show-glob
