version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Install yq
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64 &&
            sudo add-apt-repository ppa:rmescandon/yq &&
            sudo apt update &&
            sudo apt install yq
      - run:
          name: Generate config
          command: |
            chmod +x ./.circleci/generate-circleci-matrix
            ./.circleci/generate-circleci-matrix \
              -c "${CI_CUSTOMERS_TO_DEPLOY_NO_COMMA}" \
              -e "${CI_ENVS_TO_DEPLOY}" \
              -x "${CI_DEPLOY_EXCLUSIONS:-}" \
            | tee /dev/tty


workflows:
  setup:
    jobs:
      - setup
