version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker
      - run: ${DOCKER_COMPOSE} -v
      
workflows:
  staging-daily:
    jobs:
    - test
