version: 2.1

jobs:
  check-memory:
    docker:
      - image: usdotfhwastoldev/carma-base:develop
    steps:
      - run: grep 'model name' /proc/cpuinfo | wc -l
          
workflows:
  memoire:
    jobs:
      - check-memory

