version: 2.1

jobs:
  next-gen:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: docker-compose -v
      
  legacy:
    docker:
      - image: circleci/buildpack-deps
    resource_class: small
    steps:
      - run: docker-compose -v
     
           
workflows:
  ci:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
    jobs:
    - next-gen
    - legacy
