version: 2.1
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo << parameters.branch >>
          echo ${<< parameters.branch >>}
          sudo ifconfig -a

workflows:
  my-workflow:
    jobs:
      - regular-job:
          branch: << pipeline.git.branch >>
