version: 2.1
  
jobs:
  setup:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: |
          while true
            do
              cat toto.txt
              echo "Still here...."
            done

          
workflows:
  build-deploy:
    jobs:
      - setup
