version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
jobs:
  terraform-validate:
    docker:
      - image: cimg/base:2020.08
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: "1.1.2"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  terraform-validate:
    jobs:
      - terraform-validate
