version: 2.1
  
executors:
  base:
    resource_class: small
    docker:
      - image: cimg/base:2022.12
      
jobs:
  remote:
    docker:
#         - image: cimg/base:2022.12
        - image: google/cloud-sdk:410.0.0-alpine
    steps:
      - run: |
          touch package.json
          #echo -e "version 1.23 \n blofkwedflwiuehf \n version v.5.5" > package.json
          cat package.json | grep version | head -1
      
workflows:
  test:
    jobs:
      - remote
