version: 2.1
  
jobs:
  setup:
    docker:
      - image: google/cloud-sdk@sha256:e9db2327807bf8215bdd9768e7ae6afa154585ec78d0c5088fd99dabd53cc518
    steps:
      - run: |
          mkdir ~/project/tmp
          echo "Hello file" > ~/project/tmp/toto.txt
          kubectl -v
      - persist_to_workspace:
          root: tmp
          paths:
            - toto.txt
  space:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: tmp
      - run: cat tmp/toto.txt
      
          
workflows:
  build-deploy:
    jobs:
      - setup
      - space:
          requires:
            - setup
