version: 2.1

executors:
  main:
    docker:
      - image: cimg/ruby:2.5.7
commands:
  
  check-something:
    steps:
      - run: |
          ssh -N -f -L 2040:${QA_RDS_HOSTNAME}:5432 ${QA_BASTION_USERNAME}@${QA_BASTION_HOSTNAME}

jobs:
  build:
    executor: main
    steps:
      - check-something
      
workflows:
  workflow1:
    jobs:
      - build
