version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  bullish:
    docker:
      - image: cimg/base

    steps:
      - checkout
      - run:
          name: "Read ruby version"
          command: echo 'export RUBY_VERSION="3.1.2"' >> $BASH_ENV
      - run: echo $RUBY_VERSION
      - ruby/install:
          version: $RUBY_VERSION
      
workflows:
  workflow1:
    jobs:
      - bullish
