version: 2.1
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo << parameters.branch >>
          echo ${<< parameters.branch >>}
      - when:
          condition:
            or:
            - equal: [ "beeboo123", << parameters.branch >> ]

          steps:
            - run: |
                echo << parameters.branch >>
                echo "It works!"

workflows:
  my-workflow:
    jobs:
      - regular-job:
          branch: << pipeline.git.branch >>
