version: 2.1
jobs:
  regular-job:
    docker:
      - image: cimg/android:2022.04
    steps:
      - run: |
          echo Hello

workflows:
  my-workflow:
    jobs:
      - regular-job
      - approval-job:
          type: approval
          context:
            - slouck
