version: 2.1

jobs:
  build:
    parameters:
      greeting:
        type: string
        default: helli;hello
    docker:
      - image: cimg/android:2022.04
    steps:
      - run: echo "<< parameters.greeting >>"

workflows:
  unit-test-workflow:
    jobs:
      - build:
          matrix:
            alias: daily
            parameters:
              greeting: ["system-images;android-30;google_apis;x86", "system-images;android-29;google_apis;x86", "system-images;android-28;google_apis;x86", "system-images;android-27;google_apis;x86"]
          name: daily-android-test-<<matrix.greeting>>
  
  nightly-test-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build: 
          matrix:
            alias: nightly
            parameters:
              greeting: ["system-images;android-30;google_apis;x86", "system-images;android-29;google_apis;x86", "system-images;android-28;google_apis;x86", "system-images;android-27;google_apis;x86"]
          name: nightly-android-test-<<matrix.greeting>>
