version: 2.1

jobs:
  job-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   git clone --branch another-pr --single-branch --depth 1 https://github.com/XkuzemyFrench/restore-cache.git .
                   git fetch --depth=1 --force origin "another-pr:remotes/origin/another-pr"
                   git checkout -q -B another-pr
                   
workflows:

  whodidthis:
    jobs:
      - job-1
