version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          if git diff --name-only HEAD HEAD~1 | grep -q "packages/lane-mobile\|packages/lane-shared\|packages/react-native" || [ "${CIRCLE_BRANCH}" == "develop" ]; then
            echo "Changes in packages/lane-mobile, or we are building develop."
            echo "Building a new Android app..."
          else
            echo "No changes in packages/lane-mobile, not building a new app."
            circleci-agent step halt
          fi
          
                
workflows:
  build-deploy:
    jobs:
      - setup
