version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  terraform-validate:
    jobs:
      - terraform-validate:
