version: 2.1

orbs:
  my-orb:
    commands:
      my_command:
        steps:
          - run:
              name: "Printing a pipeline value"
              command: <<include(scripts/print.sh)>>
jobs:
  my_job:
    executor: cimg/base:2023.02
    steps:
      - checkout
      - my/orb/my_command

workflows:
  main:
    jobs:
      - my_job
