version: 2.1

jobs:
  master-build:
    docker:
      - image: node:14.18.2-alpine sh
    steps:
      - run: apk --no-cache add bash
      - run: bash && type -a npm

workflows:
  ci:
    jobs:
      - master-build
