version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          git diff --name-only HEAD HEAD~1 | grep "packages/lane-mobile\|packages/lane-shared\|packages/react-native"
                
workflows:
  build-deploy:
    jobs:
      - setup
