version: 2.1
    
jobs:
  setup:
    machine:
      image: true
    steps:
      - run: |
          aws --version
# Comment here 😃           
                
workflows:
  build-deploy:
    jobs:
      - setup
