version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
#       version: edge
    environment:
      APP_VERSION: "4.5.0"
    steps:
      - run:
          name: Set APP_VERSION
#           shell: cmd.exe
          command: |
            $env:APP_VERSION
            $env:LA_VERSION = "1.2.3"
            setx APP_VERSION $env:LA_VERSION /M
            refreshenv
            $env:APP_VERSION

#           shell: bash
#           command: |
#             curl --request PUT --url https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION \
#             --header 'content-type: application/json' \
#             --header "Circle-Token: $API_TOKI" \
#             --data '{"value":"4.5.0"}'
            
#           command: |  
#             $uri = "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION"
#             $headers = @{
#                 "Circle-Token" = "$env:API_TOKI"
#                 "content-type" = "application/json"
#             };
#             $body = @{
#                 value = "4.5.0"
#             }

#             Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

      - run:
          command: |
             $env:APP_VERSION = Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' APP_VERSION
             $env:APP_VERSION

#       - run:
#           command: |
#             $TOKEN = $env:API_TOKI
#             $CurlArgument = '--request', 'PUT',
#                '--url', 'https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION',
#                '--header', 'content-type=application/json',
#                '--header', 'Circle-Token=$TOKEN',
#                '--data', 'value="1.2.3"'
                
#             curl.exe @CurlArgument

#           command: |
#             $APP_VER = "1.2.3"
#             $uri = "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION"
#             $headers = @{
#                 "Circle-Token" = "$env:API_TOKI"
#                 "content-type" = "application/json"
#             };
#             $body = @{
#                 value = "$APP_VER"
#             }

#             Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

#           shell: bash
#           command: |
#             curl --request PUT --url "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION" \
#             --header 'content-type: application/json' \
#             --header "Circle-Token: $API_TOKI" \
#             --data '{"value":"1.2.3"}'

      - run:
          command: |
            $env:APP_VERSION
            
#       - run:
#           name: Delete APP_VERSION env var
#           command: |  
#             $uri = "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION"
#             $headers = @{
#                 "Circle-Token" = "$env:API_TOKI"
#             }

#             Invoke-RestMethod -Method Delete -Uri $uri -Headers $headers

workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
