version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
#   path-filtering: circleci/path-filtering@0.1.2

jobs:
  set-job:
     docker:
      - image: cimg/base:stable
      
     steps:
       - checkout
#        - run:
#            command: |
#                echo '{ "further": true }' >> /home/circleci/parameters.json
       - continuation/continue:
          configuration_path: ./.circleci/continue.yml
          parameters: /home/circleci/parameters.json
#   set-params:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run: echo "Hello"
#       - path-filtering/set-parameters:
#           mapping: |
#                   packages/.* run-path-a true
#                   special-dir/.* run-path-b true
#           base-revision: << pipeline.git.base_revision >>
#           config-path: .circleci/continue.yml
#       - run: |
#           jq '. + {"testing": "'"$CIRCLE_BUILD_NUM"'"}' /tmp/pipeline-parameters.json > /tmp/temp.json
#       - run: cat /tmp/temp.json


workflows:
  setup-workflow:
    jobs:
      - set-job
#       - set-params
#       - path-filtering/filter:
#           mapping: |
#                   packages/.* run-path-a true
#                   special-dir/.* run-path-b true
#           base-revision: << pipeline.git.base_revision >>
#           config-path: .circleci/continue.yml
