version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: export alias liststuff="ls -al"
           
      - run: |
          source ~/. bashrc
          liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
