# version: 2.1
  
# jobs:
#   setup:
#     machine:
#       image: ubuntu-2004:202010-01
#     steps:
#       - run:
#           name: Docker version
#           command: |
#             docker --version

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

executors:
  myexec:
    machine:
      image: ubuntu-2004:202104-01


commands:

jobs:

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "70194"
          executor: myexec

          post-steps:
            - run: docker --version
      
          
# workflows:
#   build-deploy:
#     jobs:
#       - setup
