version: 2.1
orbs: 
  jira: circleci/jira@1.3.1
  
parameters:
  custom-context:
    type: string
    default: Lecontext
jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: npx cypress info
           
workflows:
  build:
    jobs:
      - condy_pull:
          context: << pipeline.parameters.custom-context >>
#           post-steps:
#             - jira/notify:
#                 issue_regexp: '[A-Z]{2,30}-[0-9]+'
