version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: ./script.sh
      - slack/notify
          custom: |
            {"blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "$MESSAGE" }}]}
          
workflows:
  build-deploy:
    jobs:
      - setup
