version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  master-build:
    executor: docker/docker
    steps:
      - docker/install-docker

workflows:
  version: 2
  ci:
    jobs:
      - master-build
