version: 2.1

jobs:
  master-build:
    docker:
      - image: node:14.18.2-alpine
    steps:
      - run: apk --no-cache add bash
      - run: |
          bash -c 'hash && hash npm && hash'
#          bash -c 'hash'
#          bash -c 'type -a npm'

workflows:
  ci:
    jobs:
      - master-build:
          context: Lecontext
