version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run: |
          sudo apt-get --yes update && sudo apt-get install --yes --no-install-recommends openjdk-11-jdk-headless ca-certificates-java
          
workflows:
  build-deploy:
    jobs:
      - setup
