version: 2.1

jobs:
  Docker-Base-Build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: xlarge
    steps:
      - setup_remote_docker
      - run: |
          ssh remote-docker \ curl -sSL https://downloads.apache.org/thrift/0.15.0/thrift-0.15.0.tar.gz -o thrift.tar.gz 
           
workflows:
  La-Build:
    jobs:
    - Docker-Base-Build
