version: 2
  
jobs:
  setup:
    docker:
      - image: circleci/node
        environment:
          ENVFROMPROJECT: $foo
    steps:
      - run: echo $ENVFROMPROJECT
#       - checkout
#       - setup_remote_docker
#           version: 19.03.13
#       - run: docker version
#       - run:
#           name: Build docker image
#           command: |
#             make build/image
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
