version: 2.1

jobs:
  show-val:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - run: 
          command: |
            echo 'export PYTHON_VERSION_GLOB=$(python --version | cut -d " " -f 2)' >> $BASH_ENV
            echo $PYTHON_VERSION_GLOB

      - run: 
          command: |
            echo $PYTHON_VERSION_GLOB
      - restore_cache:
          keys:
            - v3-{{ .Environment.PYTHON_VERSION_GLOB }}

  petit-job:
    docker:
      - image: cimg/base:2022.11
    resource_class: small
    steps:
      - run: 
          command: |
            echo "Hello le world"
workflows:
  La-Build:
    jobs:
    - show-val
  da-best:
    jobs:
    - petit-job
