version: 2.1

jobs:
  master-build:
    docker:
      - image: node:14.18.2-alpine
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run: docker run -it node:14.18.2-alpine sh
      - run: ssh remote-docker \ apk --no-cache add bash
      - run: ssh remote-docker \ bash -c 'type -a npm'

workflows:
  ci:
    jobs:
      - master-build
