version: 2.1
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
    parameters:
      branch:
        type: env_var_name
        default: CIRCLE_BRANCH
    steps:
      - run: |
          echo << parameters.branch >>
          echo ${<< parameters.branch >>}
      - when:
          condition:
            or:
            - equal: [ beeboo, ${<< parameters.branch >>} ]

          steps:
            - run: |
                echo << parameters.branch >>
                echo "It works!"

workflows:
  my-workflow:
    jobs:
      - regular-job
