version: 2.1
    
jobs:
  setup:
    docker:
      - image: node@sha256:ab6c8cd32006f8a4c1c795e55ddfbc7f54f5a3fb7318506ecb355cab8f5e7182
    steps:
      - run: |
          node -v
          
                
workflows:
  build-deploy:
    jobs:
      - setup:
          name: /🧹 Emoji
