version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
#       version: edge
    environment:
      APP_VERSION: "4.5.0"
    steps:
      - run:
          name: Set APP_VERSION
          command: |
            # $env:APP_VERSION
            $LA_VERSION = "1.2.3"
            setx APP_VERSION $LA_VERSION
            #$env:APP_VERSION
            # refreshenv
            # $env:APP_VERSION
            echo $APP_VERSION

      - run:
          command: |
            # $env:APP_VERSION
            echo $APP_VERSION
            
      - when:
          condition:
            equal: [ "1.2.3", $env:APP_VERSION ]
          steps:
            - run: echo "1.2.3, viva l'Algérie"


workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
