version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: echo 'export alias liststuff="ls -al"' >> $BASH_ENV
           
      - run: |
          source ~/.bashrc
          liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
