version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: |
          echo 'export alias liststuff="ls -al"' >> $BASH_ENV
          echo 'export TOTO="Boo!"' >> $BASH_ENV
          
      - run: echo $TOTO
          
      - run: |
          echo $TOTO
          source ~/.bashrc
          liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
