version: 2.1


jobs:
  bob:
    machine:
      image: ubuntu-2004:202101-01
      
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:0f:cf:81:16:ba:54:c8:81:31:16:77:22:02:b1:4f"
            
            
      - run: docker run --rm -v ~/.ssh/config:/home/circleci/.ssh/config:ro --mount type=bind,source=/etc/passwd,target=/etc/passwd,readonly --mount type=bind,source=/etc/group,target=/etc/group,readonly -u $(id -u $USER):$(id -g $USER) -w /home/circleci/.ssh/config cimg/node:14.10.1 pwd && ls -al

                 
workflows:
  workflow-bob:
    jobs:
      - bob




