version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
          
workflows:
  build-deploy:
    jobs:
      - setup
