version: 2.1
  
# jobs:
#   setup:
#     machine:
#       image: ubuntu-2004:202010-01
#     steps:
#       - run:
#           name: Docker version
#           command: |
#             docker --version

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:11.0
    
    steps:
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Check jFrog CLI version
          command: ./jfrog --version


workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      
          
# workflows:
#   build-deploy:
#     jobs:
#       - setup
