version: 2.1
orbs:
  localstack: localstack/platform@1.0
jobs:
  run-integration-tests:
    docker:
      - image: image: cimg/base:2022.08
      - image: localstack/localstack
       environment:
         LOCALSTACK_HOSTNAME: http://localstack.fax-transmitter.com:4566
          
    steps:
      - run:
          command: echo "Execute your tests here :)"
workflows:
  integration-test:
    jobs:
      - run-integration-tests
