version: 2.1

commands:
  testscheck:
    steps:
#       - attach_workspace:
#           at: .
      - run: pwd
#       - run: touch .env
      - run: echo $SSH_AUTH_SOCK
      - run: cat .env
      - run: |-
          source .env
          echo $SSH_AUTH_SOCK

          echo RUN_TESTS $RUN_TESTS
          if [ "$RUN_TESTS" != "true" ]; then
            echo Terminating - $RUN_TESTS not specified
            circleci-agent step halt
          fi
          
executors:
  main:
    docker:
      - image: circleci/python:3.6-stretch-node

jobs:
  build:
    executor: main
    steps:
      - checkout
      - testscheck
      - run: echo "didnt fail"

workflows:
  workflow1:
    jobs:
      - build
