---

version: 2.1

orbs:
  jq: circleci/jq@2.2
 
parameters:
  param1:
    type: string
    default: batman
  param2:
    type: string
    default: robin
  param3:
    type: string
    default: I-am-<< pipeline.parameters.param1 >>
  param4:
    type: boolean
    default: true
    
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
    environment:
      BILLBOOL: << pipeline.parameters.param4 >>
#     parameters:
#       branch:
#         type: string
    steps:
      - run: |
          echo << pipeline.parameters.param1 >>
          echo << pipeline.parameters.param2 >>
          echo << pipeline.parameters.param3 >>
          echo $BILLBOOL
      - jq/install

workflows:
  my-workflow:
#     when:
#       equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - regular-job
#           post-steps:
#             - jira/notify:
#                 environment_type: production
#                 job_type: deployment
          
#           filters:
#             branches:
#               only:
#                 - caramba
