version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          name: Set APP_VERSION default value
          shell: bash
          command: |
            curl --request PUT --url https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION \
            --header 'content-type: application/json' \
            --header "Circle-Token: $API_TOKI" \
            --data '{"value":"4.5.0"}'

      - run:
          command: |
            $env:APP_VERSION

      - run:
          command: |
            $TOKEN = $env:API_TOKI
            $CurlArgument = '--request', 'PUT',
               '--url', 'https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION',
               '--header', 'content-type=application/json'',
               '--header', 'Circle-Token=$TOKEN',
               '--data', 'value="1.2.3"'
                
            curl.exe @CurlArgument

#           command: |
#             $uri = "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION"
#             $headers = @{
#                 'Circle-Token' = '$env:API_TOKI'
#                 'content-type' = 'application/json'
#             }
#             $body = @{
#                 value = "1.2.3"
#             }

#             Invoke-RestMethod -Method 'Put' -Uri $uri -Headers $headers -Body $body

#           shell: bash
#           command: |
#             curl --request PUT --url "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION" \
#             --header 'content-type: application/json' \
#             --header "Circle-Token: $API_TOKI" \
#             --data '{"value":"1.2.3"}'
      - run:
          command: |
            $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build:
          context: ravinder
