version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          name: Set APP_VERSION default value
          command: |
            curl --request PUT --url https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION \
            --header 'content-type: application/json' \
            --header "Circle-Token: $API_TOKI" \
            --data '{"value":"4.5.0"}'
            $env:APP_VERSION
            
      - run:
          shell: bash
          command: |
            curl --request PUT --url https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION \
            --header 'content-type: application/json' \
            --header "Circle-Token: $API_TOKI" \
            --data '{"value":"1.2.3"}'
      - run:
          command: |
            $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build:
          context: ravinder
