version: 2.1

jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: cypress --version
           
workflows:


  staging-master:
    jobs:
      - condy_pull
