version: 2
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: checkmarx/cx-flow
  
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
