version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:12.13
    resource_class: medium

    steps:
      - run: |
          echo $PATH
          ls -al ~/.nvm/versions
      - run:
          name: setup bazel
          command: npm --version
            
workflows:
  push:
    jobs:
      - test
