version: 2.1

# orbs:
#   my-orb:
#     commands:
#       my_command:
#         steps:
#           - run:
#               name: "Printing a pipeline value"
#               command: echo "<< pipeline.id >>"
jobs:
  my_job:
    docker:
      - image: cimg/base:2023.02
    steps:
      - run: echo "<< pipeline.id >>"
#       - checkout
#       - my-orb/my_command

workflows:
  main:
    jobs:
      - my_job
