version: 2.1

executors:
  main:
    docker:
      - image: circleci/ruby:2.5.7-buster-node-browsers

jobs:
  build:
    executor: main
    steps:
      - run: |
          sudo apt-get install libpq-dev

workflows:
  workflow1:
    jobs:
      - build
