version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |     
          #echo \'export BLA=\'$(cat notif.txt| awk '{printf "%s\\n", $0}' | sed 's/\"/\\"/g') \'\' >> $BASH_ENV
          #cat notif.txt|sed ':a;N;$!ba;s/\n/\\n/g'|sed 's/\"/\\"/g' > message.txt
          #cat notif.txt|awk '{printf "%s\\n", $0}'|sed 's/\"/\\"/g' > message.txt
          
          #cat notif.txt | sed 's/\"/\\"/g' > message.txt ####  Doesn't work > parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 13, column 41
          
          cat notif.txt|awk '{printf "%s\\n", $0}' > message.txt

          echo 'export MESSAGE="*Changes to be applied from terraform:* \`\`\`$(cat message.txt)\`\`\`" ' >> $BASH_ENV
          #echo 'export "GOOD_MESS=$(echo \"$MESSAGE\" | awk \'{printf "%s\\n", $0}\'|sed \'s/\"/\\"/g\')'
          source $BASH_ENV
          #echo $BLA
          echo $MESSAGE
          #echo$$GOOD_MESS
      - slack/notify:
          custom: |
            {"blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "$MESSAGE" }}]}
          
workflows:
  build-deploy:
    jobs:
      - setup:
          context: slouck
