version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.1.2

jobs:
  set-params:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - path-filtering/set-parameters:
          mapping: |
                  packages/.* run-path-a true
                  special-dir/.* run-path-b true
          base-revision: << pipeline.git.base_revision >>
      - run: |
          jq '. + {"testing": "'"$CIRCLE_BUILD_NUM"'"}' /tmp/pipeline-parameters.json > /tmp/temp.json
      - run: cat /tmp/temp.json

workflows:
  setup-workflow:
    jobs:
      - set-params
