version: 2.1
  
jobs:
  cimg:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - run:
          command: gem install bundler -v 2.2.17
          
      - run: ls -al /home/circleci
      
  circleci:
    docker:
      - image: circleci/ruby:2.6.6-node
    steps:
      - run:
          command: gem install bundler -v 2.2.17
          
      - run: ls -al /home/circleci

          
workflows:
  build-deploy:
    jobs:
      - cimg
      - circleci
