version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |     
          echo 'export BLA="$(cat notif.txt)"' >> $BASH_ENV
          echo 'export MESSAGE="Changes to be applied from terraform: \`\`\`$BLA\`\`\`" ' >> $BASH_ENV
          source $BASH_ENV
      - slack/notify:
          custom: |
            {"blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "$MESSAGE" }}]}
          
workflows:
  build-deploy:
    jobs:
      - setup:
          context: slouck
