version: 2.1

jobs:
  travail:
    working_directory: ~/project/wksp
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      
      - run: |
          ls -al wksp
          pwd
      - persist_to_workspace:
          root: .
          paths:
            - .
      
  leworkspace:
    working_directory: ~/project/wksp
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      - run: ls -al
      - attach_workspace:
          at: ~/project/wksp
      - run: ls -al
                   
workflows:

  whodidthis:
    jobs:
      - travail
      - leworkspace:
          requires:
            - travail
