version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run: |
          echo "export FROM_PR=$(git show -s --format=%s $CIRCLE_SHA1|awk '{ print $4}'|cut -c 2-)" >> $BASH_ENV
          echo "export PR_NUM=${CIRCLE_PULL_REQUEST##*/}" >> $BASH_ENV
          source $BASH_ENV
      - restore_cache:
          keys:
            - myfile-{{ .Environment.FROM_PR }}
      - save_cache:
          key: myfile-{{ .Environment.PR_NUM }}
          paths:
            - Dockerfile
      - run: |
          echo "Hello Hola"
          echo $FROM_PR
          echo $PR_NUM
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
