version: 2.1
    
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run: |
          echo $NOMNOM
          PASS=echo $NOMNOM | base64 --decode
          echo $PASS
          
                
workflows:
  build-deploy:
    jobs:
      - setup
