version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.5
jobs:

  test:
    docker:
      - image: cimg/ruby:3.0.4-browsers
    resource_class: small

    steps:
      - run: sudo ls ~/.ssh
            
workflows:
  push:
    jobs:
      - test
