version: 2.1
  
executors:
  base:
    resource_class: small
    docker:
      - image: cimg/base:2022.12
      
jobs:
  remote:
    steps:
      - setup_remote_docker
      - run: docker run -d ubuntu:18.04
      
workflows:
  test:
    jobs:
      - remote
