version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker:
          version: 20.10.07
      
          
workflows:
  build-deploy:
    jobs:
      - setup
