version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: hashicorp/terraform:0.14.11
    steps:
      - run:
          name: Is curl here?
          command: |
              sudo apt-get update && apt-get install curl
              curl checkip.amazonaws.com 
      
      
          
workflows:
  build-deploy:
    jobs:
      - setup
