version: 2.1

jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: echo << pipeline.git.branch >>
           
workflows:


  staging-master:
    jobs:
      - condy_pull
      
      - hold265: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
          requires:
            - condy_pull
