version: 2.1

parameters:
  recipient:
    type: string
    default: "Toto"

commands:
  sayhello:
    parameters:
      to:
        type: string
        default: "World"
        description: "Hello to whom?"
      
    steps:
      - run: echo "Hello <<parameters.to>>"
      
jobs:
  le-job:
    docker:
      - image: cimg/base:2023.01
    steps:
      - run: |
          echo "export QUI=<< pipeline.parameters.recipient >>" >> $BASH_ENV
          source $BASH_ENV
      - run: echo "$QUI"
      - sayhello:
          to: $QUI
           
workflows:
  build:
    jobs:
      - le-job
