version: 2.1

jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: echo << pipeline.git.branch >>
           
workflows:
  staging-pull:
    when:
      matches:
        pattern: "^circleci.*$"
        value: << pipeline.git.branch >>
    jobs:
    - condy_pull

  staging-master:
    when:
      matches:
        pattern: "^master$"
        value: << pipeline.git.branch >>
    jobs:
    - condy_pull
