version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - my-special-file-{{ checksum "./special-dir/*" }}
      - save_cache:
          key: my-special-file-{{ checksum "./special-dir/*" }}
          paths:
            - /packages
      - run: |
          echo "Hello Hola"
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
