version: 2.1
jobs:
  nvm-ess:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - run: |
          which nvm
          nvm --version
          which npm
          npm --version

workflows:
  build:
    jobs:
      - nvm-ess
