version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      - run:
          name: Build docker image
          command: |
            make build/image
      
workflows:
  build-deploy:
    jobs:
      - setup
