version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: sleep 300
          background: true
          no_output_timeout: 4m
          
workflows:
  build-deploy:
    jobs:
      - setup
