version: 2.1

jobs:
  travail:
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      
      - run: |
          ls -al wksp
          pwd
          echo "toto" > ~/project/wksp/new-file.txt
      - persist_to_workspace:
          root: ~/project/wksp
          paths:
            - new-file.txt
      
  leworkspace:
    docker:
      - image: cimg/node:10.24.0
    steps:
      - checkout
      - run: |
          pwd
          ls -al
      - attach_workspace:
          at: ~/project/wksp
      - run: |
          cd wksp
          pwd
          ls -al
                   
workflows:

  whodidthis:
    jobs:
      - travail
      - leworkspace:
          requires:
            - travail
