version: 2.1

executors:
  main:
    docker:
      - image: cimg/ruby:2.5.7

jobs:
  build:
    executor: main
    steps:
      - run: |
          sudo apt-get update && sudo apt list --installed|grep libpq

workflows:
  workflow1:
    jobs:
      - build
