# version: 2.1
  
# jobs:
#   setup:
#     docker:
#       - image: circleci/node
#     steps:
#       - checkout
#       - setup_remote_docker
# #           version: 20.10.7
#       - run: docker build .
          
# workflows:
#   build-deploy:
#     jobs:
#       - setup

version: 2.1

jobs:
  build:
    docker:
      - image: unityci/editor:2019.4.19f1-linux-il2cpp-0
    steps:

      - run:
          name: What SSH version?
          command: ssh -V
  
workflows:
  build-deploy:
    jobs:
      - build
