version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:12.13
    resource_class: medium

    steps:
      - run: |
          sudo sed -i 's/\/usr\/bin\/env[[:space:]]node/home\/circleci\/\.nvm\/versions\/node\/v12\.13\.1\/bin\/node/' ~/.nvm/versions/node/v12.13.1/bin/npm
          echo "export PATH="$PATH:.nvm/versions/node/v12.13.1/bin" >> $BASH_ENV
      - run:
          name: setup bazel
          command: npm --version
            
workflows:
  push:
    jobs:
      - test
