version: 2.1
jobs:
  build-arm-large:
    machine:
      image: ubuntu-2004:current
      
    steps:
      - run: uname -a
      - run: docker-compose --version
      - run: 
          command: |
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

      - run: docker-compose --version


workflows:
  build:
    jobs:
      - build-arm-large
