version: 2.1

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello << parameters.to >>"

jobs:
  master-build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: echo 'export ISSUE_KEY="123"' >> $BASH_ENV
      - run:
          name: test result
          command: source $BASH_ENV
      - greeting:
          to: $ISSUE_KEY
workflows:
  version: 2
  ci:
    jobs:
      - master-build
