version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    environment:
      APP_VERSION: "4.5.0"
    steps:
      - run:
          command: |
            $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build
