version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |     
          echo 'export BLA="$(cat notif.txt)"' >> $BASH_ENV
          echo 'export MESSAGE="Changes to be applied from terraform: \`\`\`$BLA\`\`\`" ' >> $BASH_ENV
          echo 'export "GOOD_MESS=$(echo \"$MESSAGE\" | awk \'{printf "%s\\n", $0}\'|sed \'s/\"/\\"/g\')'
          source $BASH_ENV
          echo $BLA
          echo $MESSAGE
          echo$$GOOD_MESS
      - slack/notify:
          custom: |
            {"blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "$GOOD_MESS" }}]}
          
workflows:
  build-deploy:
    jobs:
      - setup:
          context: slouck
