version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run: |
          echo $BB_admin_username
          echo 'export "BB_admin_username=perrytheplatypus"' >> $BASH_ENV

      - run: echo $BB_admin_username


workflows:
  papu:
    jobs:
      - premier
   
