version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-cli: circleci/aws-cli@2.0.6

executors:
  le-202111-ubuntu:
    machine:
#       image: ubuntu-2004:202111-01
      docker_layer_caching: true

workflows:
  build-test:
    jobs:
      - aws-ecr/build-and-push-image:
          pre-steps:
            - checkout
            - aws-cli/setup:
                override-installed: true
#                 version: 2.3.4
            - run: aws --version
          repo: al-test
          executor: le-202111-ubuntu
