version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build docker image
          command: |
            docker build -t myim:1.0 .
      
workflows:
  build-deploy:
    jobs:
      - setup
