version: 2.1
  
executors:
  base:
    resource_class: small
    docker:
      - image: cimg/base:2022.12
      
jobs:
  remote:
    docker:
        - image: cimg/base:2022.12
    steps:
      - run: |
          touch package.json
          cat package.json | grep version | head -1
      
workflows:
  test:
    jobs:
      - remote
