version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:2021.07

jobs:
  build:
    executor: main
    steps:
      - run: |
          ssh -V

workflows:
  workflow1:
    jobs:
      - build
