version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: sleep 5
          name: build/static-content/linux

          
workflows:
  build-deploy:
    jobs:
      - setup
