version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: |
          sudo echo 'alias liststuff="ls -al"' > ~/.bash_aliases
          source ~/.bashrc
          cat ~/.bash_aliases
          liststuff
      
      - run: |
          source ~/.bashrc
          liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
