version: 2.1

jobs:
  check-memory:
    docker:
      - image: usdotfhwastoldev/carma-base:develop
    steps:
      - run: ulimit -a | grep stack
          
workflows:
  memoire:
    jobs:
      - check-memory

