version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - run: git show-ref --head --dereference
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
