version: 2.1
  
# jobs:
#   setup:
#     machine:
#       image: ubuntu-2004:202010-01
#     steps:
#       - run:
#           name: Docker version
#           command: |
#             docker --version

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: circleci/golang:1.16
    
    steps:
      - run: |
            sudo apt-get --allow-releaseinfo-change-suite update
            
            sudo apt-get update
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            
            sudo apt-get update
            sudo apt-get install azure-cli

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      
          
# workflows:
#   build-deploy:
#     jobs:
#       - setup
