version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default

    steps:
      - run:
          shell: powershell.exe
          command: |
            New-Item -Path "c:\tmp" -Name "testfile1.txt" -ItemType "file" -Value "This is a text string."
            Get-Item C:\tmp\* | Remove-Item -Path C:\tmpa\*.txt -Force

workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
