version: 2.1
orbs: 
  jira: circleci/jira@1.3.1
  
jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: |
          echo Hellooooowwwwwwww
      - jira/notify
           
workflows:
  build:
    jobs:
      - condy_pull:
          name: Condy Pull
          post-steps:
            - jira/notify:
                issue_regexp: '[A-Z]{2,30}-[0-9]+'
                environment_type: development
                job_type: deployment
                scan_commit_body: true
