version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:


      - setup_remote_docker:
          version: 20.10.14
          
      - run: docker run cimg/node:18.10.0
      
      - run: |
          dockerize -wait tcp://remote-docker:5432 -timeout 1m
          
      - run: |
          curl remote-docker:5432

workflows:
  papu:
    jobs:
      - premier
   
