version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: |
          echo 'export liststuff="ls -al"' >> $BASH_ENV
          mkdir mydir
          echo 'export MYDIR=mydir'>> $BASH_ENV 
      
      - run: |
          touch $MYDIR/text.txt
          bash -c "$liststuff $MYDIR"
          
workflows:
  build-deploy:
    jobs:
      - setup
