version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:edge #public.ecr.aws/eks-distro/kubernetes/pause:3.6
    steps:
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true
      - checkout
      - run: docker run --name web-server -p 80:80 -d nginx:stable-alpine
      - run: docker network ls
      - run: docker network inspect bridge

workflows:
  workflow1:
    jobs:
      - build
