version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: node:14.18.2-alpine
    steps:
      - run: apk --no-cache add bash
      - run: |
          bash -c 'hash && hash npm && hash'
          sleep 41
          bash -c 'hash'
#          bash -c 'type -a npm'

workflows:
  ci:
    jobs:
      - show-pr-refs
