version: 2.1
orbs: 
  jira: circleci/jira@1.3.1
jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: npx cypress info
           
workflows:
  staging-master:
    jobs:
      - condy_pull:
          post-steps:
            - jira/notify
