version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:2020.08

jobs:
  build:
    executor: main
    steps:
      - setup_remote_docker:
          version: 19.03.13

      - run: |
          ssh remote-docker \ lsb_release -a
          ssh remote-docker \ uname -r

workflows:
  workflow1:
    jobs:
      - build
