---

version: 2.1

orbs:
  jira: circleci/jira@1.3.1
 
parameters:
  param1:
    type: string
    default: batman
  param2:
    type: string
    default: robin
  param3:
    type: string
    default: I-am-<< pipeline.parameters.param1 >>
    
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
#     parameters:
#       branch:
#         type: string
    steps:
      - run: |
          echo << pipeline.parameters.param1 >>
          echo << pipeline.parameters.param2 >>
          echo << pipeline.parameters.param3 >>

workflows:
  my-workflow:
    when: [ api, << pipeline.trigger_source >> ]
    jobs:
      - regular-job:
          post-steps:
            - jira/notify:
                environment_type: production
                job_type: deployment
          
#           filters:
#             branches:
#               only:
#                 - caramba
