version: 2.1

jobs:
  job-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
             git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
             
             git clone --depth 1 --branch "$CIRCLE_BRANCH" $CIRCLE_REPOSITORY_URL .
             git checkout -q -B "$CIRCLE_BRANCH"
                   
workflows:

  whodidthis:
    jobs:
      - job-1
