version: 2.1
  
jobs:
  setup:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: |
          sudo apt update
          sudo apt -y install software-properties-common
          sudo add-apt-repository ppa:fkrull/deadsnakes
          sudo apt update
          sudo apt install -y python3.8
          sudo python --version
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" \
              -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      
          
workflows:
  build-deploy:
    jobs:
      - setup
