version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: |
          sudo echo 'alias liststuff="ls -al"' >> ~/.bashrc
          source ~/.profile
      
      - run: liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
