version: 2.1

jobs:
  publish-feature:
    docker:
      image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - setup_remote_docker
#       - checkout
#       - my-orb/my_command

workflows:
  main:
    jobs:
      - publish-feature
