version: 2.1

jobs:
  succeilure:
    docker:
      - image: cimg/python:3.9
    resource_class: small

    steps:           
      - run:
          shell: /bin/bash +e
          name: Failing step
          command: exit 1

      - run:
          when: always
          command: echo "Helloooooo"

          
workflows:
  La-Build:
    jobs:
    - succeilure
