---

version: 2.1
    
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
#     parameters:
#       branch:
#         type: string
    steps:
      - run: |
          echo << pipeline.parameters.param1 >>
          echo << pipeline.parameters.param2 >>
          echo << pipeline.parameters.param3 >>

workflows:
  my-workflow:
    jobs:
      - regular-job
