version: 2.1

jobs:
  show-cache:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - run:
          name: Save var
          command: |
            TEST="val"
            echo 'export TEST="${TEST}"' >> "$BASH_ENV"
      - run:
          name: Read var
          command: |
            source ${BASH_ENV}
            echo ${TEST}

workflows:
  La-Build:
    jobs:
    - show-cache
