version: 2.1

executors:
  main:
    docker:
      - image: cimg/ruby:2.5.7
commands:
  
  check-something:
    steps:
      - checkout
      - run: |
          source ./script.sh
          CancelJob

jobs:
  build:
    executor: main
    steps:
      - check-something
      
workflows:
  workflow1:
    jobs:
      - build
