version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  setup:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - run: |
          mkdir supafolda
          # cp ./script.sh supafolda
      - run:
          working_directory: supafolda
          command: |
              echo 'export COMMITTER_NAME=$( curl "https://circleci.com/api/v1.1/project/${API_URL}?circle-token=${CIRCLE_API_TOKEN}" | tail -n23 | grep committer_name | cut -f2- -d: | grep -o -P "(?<=\").*(?=\")")' >> $BASH_ENV
              echo 'export COMMITTER_NAME_VAR="${COMMITTER_NAME}"' >> $BASH_ENV
              echo 'export LE_COMMIT="John"' >> $BASH_ENV
              # START reproducing 97880 #####
              #FILE="../leterraplan.json"
              #cat $FILE
              #cat $FILE|grep -E "\#" |awk '{printf "%s\\n", $0}'| sed 's/\"/\\"/g' > ~/project/message.txt
              #cat ~/project/message.txt
              #echo 'export MESSAGE="Our Changes to be applied from terraform: $(cat ~/project/message.txt)" ' >> $BASH_ENV
              # END reproducing 97880 #####
              
      - run: echo $MESSAGE
#       - run: |     
#           #echo \'export BLA=\'$(cat notif.txt| awk '{printf "%s\\n", $0}' | sed 's/\"/\\"/g') \'\' >> $BASH_ENV
#           cat notif.txt|sed ':a;N;$!ba;s/\n/\\n/g'|sed 's/\"/\\"/g' > message.txt
#           #cat notif.txt|awk '{printf "%s\\n", $0}'|sed 's/\"/\\"/g' > message.txt
          
#           #cat notif.txt | sed 's/\"/\\"/g' > message.txt ####  Doesn't work > parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 13, column 41
          
#           #cat notif.txt|awk '{printf "%s\\n", $0}' > message.txt ####  Doesn't work > parse error: Invalid numeric literal at line 7, column 183

#           echo 'export MESSAGE="*Our Changes to be applied from terraform:* \`\`\`$(cat message.txt)\`\`\`" ' >> $BASH_ENV
#           #echo 'export "GOOD_MESS=$(echo \"$MESSAGE\" | awk \'{printf "%s\\n", $0}\'|sed \'s/\"/\\"/g\')'
#           source $BASH_ENV
#           #echo $BLA
#           echo $MESSAGE
          
      - slack/notify:
                custom: |
                  {
                    "text": "",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}` , ${COMMITTER_NAME_VAR} , ${COMMITTER_NAME} , ${commit} executed by `${CIRCLE_USERNAME}`"
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Job"
                            },
                            "url": "${CIRCLE_BUILD_URL}"
                          }
                        ]
                      }
                    ]
                  }
                event: always
              
          
workflows:
  build-deploy:
    jobs:
      - setup:
          context: slouck
