version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
workflows:
  run-test:
    jobs:
      - cypress/install
      - cypress/run:
          post-install:
            - run: npm run run_e2e:au_login

          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
