version: 2.1


jobs:
  bob:
    docker:
      - image: cimg/node:14.10.1
      
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:0f:cf:81:16:ba:54:c8:81:31:16:77:22:02:b1:4f"
            
      - setup_remote_docker:
          version: 20.10.7
            
      - run: docker run -it --name=le-cont -v ~/.ssh:/home/circleci/.ssh2:ro -w /home/circleci/.ssh2 cimg/node:14.10.1 pwd && ls -al
      - run: ssh remote-docker \ ls -al /home/circleci/.ssh2
#       - run: docker cp /home/circleci/.ssh/*/ le-cont:/home/circleci/.ssh/
      - run: docker exec ls -al

                 
workflows:
  workflow-bob:
    jobs:
      - bob




