version: 2.1

orbs:
  node: 'circleci/node@4.7.0'
  serverless: 'circleci/serverless-framework@1.0.1'
  
jobs:
  setup:
    executor: serverless/default
    steps:
      - serverless/setup
      - run: sls --version

          
workflows:
  build-deploy:
    jobs:
      - setup
    context: AWS
