version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          command: |
            $env:APP_VERSION
            
      - run:
          shell: bash
          command: |
            curl PUT "https://circleci.com/api/v2/context/b5816bcd-239a-49e2-a45c-fd9026fea393/environment-variable/APP_VERSION" \
            -H "Circle-Token: $API_TOKI"
            -data '{"value":"1.2.3"}'
      - run:
          command: |
            $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build:
          context: ravinder
