version: 2.1

jobs:
  show-cache:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - run: 
          command: |
            PYTHON_VERSION=$(python --version | cut -d " " 2)
            echo $PYTHON_VERSION
            echo 'export PYTHON_VERSION_GLOB="$PYTHON_VERSION"' >> $BASH_ENV
            source $BASH_ENV
            echo $PYTHON_VERSION_GLOB
      - restore_cache:
          keys:
            - v3-{{ .Environment.PYTHON_VERSION }}

workflows:
  La-Build:
    jobs:
    - show-cache
