version: 2.1
jobs:
  master-build:
    machine:
      image: ubuntu-2004:202101-01
#       image: ubuntu-1604:202007-01
#     resource_class: large
    steps:
      - checkout
      - run: |
          OHLALA=sacrebleu!
          chmod +x ./script.sh
          ./script.sh
#       - checkout
#       - run:
#           name: Updating Java and sbt versions
#           command: |
#             sudo apt-get update
#             sudo apt install openjdk-11-jdk
#             sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
#             java -version
#             echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
#             echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
#             curl -skL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
#             sudo apt-get update
#             sudo apt-get install sbt
#             sbt sbtVersion
#             echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
#             echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
workflows:
  version: 2
  ci:
    jobs:
      - master-build
