version: 2.1

jobs:
  test:
    machine:
      image:: ubuntu-2004:202101-01
    resource_class: small

    steps:
      - run: |
          curl https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/x86_64/baseos/os/repodata/repomd.xml

workflows:
  workflow1:
    jobs:
      - test
