version: 2.1

orbs:
  linux-not: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: linux-not/default
#       version: edge
    environment:
      APP_VERSION: "4.5.0"
    parameters:
      version:
        type: env_var_name
        default: APP_VERSION
    steps:
      - run:
          name: Set APP_VERSION
          command: |
            $env:APP_VERSION
            echo ${<<parameters.version>>}
            $LA_VERSION = "1.2.3"
            setx APP_VERSION $LA_VERSION
            $env:APP_VERSION
            refreshenv
            $env:APP_VERSION
            echo ${<<parameters.version>>}

      - run:
          command: |
            # $env:APP_VERSION
            echo ${<<parameters.version>>}
            
      - run:
          shell: bash
          command: |
            echo ${<<parameters.version>>}
            
      - when:
          condition:
            equal: [ "1.2.3", "${<<parameters.version>>}" ]
          steps:
            - run: echo "1.2.3, viva l'Algérie"


workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
