version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  python: circleci/python@1.4.0
  
executors:
  base:
    resource_class: small
    docker:
      - image: cimg/base:2022.12
      
jobs:
  continue:
    executor: python/default
    steps:
      - aws-cli/install
      
      
workflows:
  test:
    jobs:
      - continue
