version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - my-{{ checksum "special-file-dir.tar.gz"}}
            
      - run: tar -czvf special-file-dir.tar.gz ./packages
            
      - save_cache:
          key: my-{{ checksum "special-file-dir.tar.gz" }}
          paths:
            - ./packages
            
      - run: |
          echo "Helloooooo"
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
