version: 2.1
    
jobs:
  my-job:
    machine:
      image: android:2022.12.1
    working_directory: ~/gelato-os-flutter
    
    steps:
      - run: |
          which gradlew

workflows:
  my-work:
    jobs:
      - my-job
