version: 2.1
    
jobs:
  regular-job:
    machine:
      image: android:2022.12.1
    working_directory: ~/gelato-os-flutter
    
    steps:
      - run: |
          which gradlew

workflows:
  my-workflow:
    jobs:
      - regular-job
