version: 2.1

jobs:
  bullish:
    docker:
      - image: cimg/python:3.10
    resource_class: small

    steps:
      - checkout
      - run:
          name: Get a stock price
          shell: /usr/bin/env python3
          command: >+
            import os

            #cmd = 'pwd'
            os.system('pwd')
            #import yfinance as yf

            #define the ticker symbol
            #tickerSymbol = 'TSLA'

            #get data on this ticker
            #tickerData = yf.Ticker(tickerSymbol)

            #get the historical prices for this ticker
            #tickerDf = tickerData.history(period='1d')

            #print(tickerDf)
      
workflows:
  workflow1:
    jobs:
      - bullish
