version: 2.1

jobs:
  bullish:
    docker:
      - image: cimg/python:3.10
    resource_class: small

    steps:
      - checkout
      - run:
          name: Get a stock price
          command: python3 script.py
      
workflows:
  workflow1:
    jobs:
      - bullish:
          filters:
            tags:
              only: /.*/
