version: 2.1

jobs:
  publish-feature:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run: echo "hello hello"
      - setup_remote_docker

workflows:
  main:
    jobs:
      - publish-feature
