version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:2021.04

jobs:
  build:
    executor: main
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          ssh remote-docker \ ping registry-1.docker.io

workflows:
  workflow1:
    jobs:
      - build
