version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default

    steps:
      - run:
          shell: bash
          command: |
            while true; do
              sleep 5
              systeminfo | find "Available Physical Memory"
              echo "======"
            done
          background: true
      - run:
#           shell: powershell.exe
          command: |
            # $ErrorActionPreference = 'Stop'
            $ErrorActionPreference
            New-Item -Path "c:\tmp" -Name "testfile1.txt" -ItemType "file" -Value "This is a text string."
            Get-Item C:\tmpa\* -Filter "*.txt" | Remove-Item -Force
            Get-Item C:\tmp\*
            sleep 10
            refresh env

workflows:
  whatos:
    jobs:
      - build
#           context: ravinder
