version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run: FROM_PR=$(git show -s --format=%s $CIRCLE_SHA1|awk '{ print $4}'|cut -c 2-)
      - restore_cache:
          keys:
            - myfile-${FROM_PR}
      - save_cache:
          key: myfile-from-pr-${CIRCLE_PULL_REQUEST##*/}
          paths:
            - Dockerfile
      - run: echo $CIRCLE_PULL_REQUEST
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
