version: 2.1

jobs:
  travaile:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - run: docker-php-ext-install
      
                   
workflows:

  whodidthis:
    jobs:
      - travaile
