version: 2.1

jobs:
  master-build:
    docker:
#       - image: node:14.18.2-alpine
      - image: node:14.18.2-alpine
    steps:
      - run: |
          hash
          hash npm
          hash
          type -a npm

workflows:
  ci:
    jobs:
      - master-build
