version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - my-{{ .Environment.Tar_Checksum }}
            
      - run: |
          tar -czvf special-file-dir.tar.gz ./packages
          Tar_Checksum_Val=$(cksum special-file-dir.tar.gz|awk '{ print $1}')
          echo $Tar_Checksum_Val
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar \
            --header "Circle-Token: $API_TOKI" \
            --header 'content-type: application/json' \
            --data '{"name":"Tar_Checksum","value":"'"${Tar_Checksum_Val}"'"}'
            
      - save_cache:
          key: my-{{ .Environment.Tar_Checksum }}
          paths:
            - ./packages
            
      - run: |
          echo "Helloooooo"
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
