version: 2.1

jobs:
  show-pr-refs:
    parameters:
       this-pr-cache:
         type: env_var_name
         default: CACHE_PR_KEY_${CIRCLE_PULL_REQUEST##*/}
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run: echo << parameters.this-pr-cache >>
      - run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar \
            --header "Circle-Token: $API_TOKI" \
            --header 'content-type: application/json' \
            --data '{"name":"'"CACHE_PR_KEY_${CIRCLE_PULL_REQUEST##*/}"'","value":"this PR file"}'
            
      - restore_cache:
          keys:
            - my-special-file-{{ .Environment.<< parameters.this-pr-cache >> }}
      - save_cache:
          key: my-special-file-{{ .Environment.<< parameters.this-pr-cache >> }}
          paths:
            - ./packages
      - run: |
          echo "Hello"
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
