version: 2.1

executors:
  main:
    docker:
      - image: cimg/ruby:3.1

jobs:
  build:
    executor: main
    steps:
      - setup_remote_docker
      - run: |
          which ruby

workflows:
  workflow1:
    jobs:
      - build
