version: 2.1
  
jobs:
  setup:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Docker version
          command: |
            docker --version
      - run: echo "toto" > file.txt
      - run: mv file.txt /var/lib/docker
      
          
workflows:
  build-deploy:
    jobs:
      - setup
