version: 2.1

jobs:
  condy_pull:
    docker:
      - image: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - run: echo "Hello Hola"
           
workflows:
  staging-pull:
    when:
      matches:
        pattern: "^circleci-project-setup$"
        value: << pipeline.git.branch >>
    jobs:
    - condy_pull
