version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: sleep 700
          background: true
#           no_output_timeout: 2m
          
      - run: sleep 660
          
workflows:
  build-deploy:
    jobs:
      - setup
