version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
#       - checkout
      - run: |
          echo 'export liststuff="ls -al"' >> $BASH_ENV
      
      - run: |
          touch text.txt
          bash -c $liststuff
          
workflows:
  build-deploy:
    jobs:
      - setup
