version: 2.1
jobs:
  regular-job:
    docker:
      - image: cimg/base:stable
#     parameters:
#       branch:
#         type: string
    steps:
      - run: |
          sudo ifconfig -a

workflows:
  my-workflow:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "beeboo", << pipeline.schedule.name >> ]
    jobs:
      - regular-job
      
  my-other-workflow:
    when:
      and:
        - equal: [ "scheduled_pipeline", << pipeline.trigger_source >> ]
        - equal: [ "beeboo", << pipeline.schedule.name >> ]
    jobs:
      - regular-job
