version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
executors:
  main:
    docker:
      - image: cimg/base:2022.01
commands:
  
  check-something:
    steps:
      - run: |
          ssh -N -f -L ${QA_RDS_HOSTNAME} ${QA_BASTION_USERNAME}@${QA_BASTION_HOSTNAME}
#          ssh -N -f -L 2040:${QA_RDS_HOSTNAME}:5432 ${QA_BASTION_USERNAME}@${QA_BASTION_HOSTNAME}
          

jobs:
  build:
    executor: main
    steps:
      - checkout
      - run: tar -cvzf archive.tar.gz ./dummy_dir
      - store_artifacts:
          path: ./archive.tar.gz
          destination: archived_folder
      
workflows:
  workflow1:
    jobs:
      - build
