version: 2.1

orbs:
  android: circleci/android@1.0.3
  
jobs:
  build:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
    executor:
      name: android/android-machine
    steps:
      - android/start-emulator-and-run-tests:
          system-image: << parameters.system-image >>


# version: 2.1


# commands:
#   salutation:
#     parameters:
#       greeting:
#         type: string
#         default: helli;hello
#     steps:
#       - run: echo << parameters.greeting >>

# jobs:
#   build:
#     parameters:
#       greeting:
#         type: string
#         default: helli;hello
#     docker:
#       - image: cimg/android:2022.04
#     steps:
#       - salutation:
#           greeting: << parameters.greeting >>

workflows:
  unit-test-workflow:
    jobs:
      - build: 
          matrix:
            alias: nightly
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
                - system-images;android-29;google_apis;x86
                - system-images;android-28;google_apis;x86
                - system-images;android-27;google_apis;x86
          name: nightly-android-test-<<matrix.system-image>>
