version: 2.1
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: checkmarx/cx-flow
  
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup:
          pre-steps:
            - run:
                name: Install git and OpenSSH
                command: |
                  apk update && apk add git openssh-client
