version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: sleep 5

          
workflows:
  build-deploy:
    jobs:
      - setup:
          name: pikachu-static-content-linux
