version: 2.1

jobs:
  show-pr-refs:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar \
            --header "Circle-Token: $API_TOKI" \
            --header 'content-type: application/json' \
            --data '{"name":"CACHE_PR_KEY","value":"'"${CIRCLE_PULL_REQUEST##*/}"'"}'
      - restore_cache:
          keys:
            - my-special-file-{{ .Environment.CACHE_PR_KEY }}
      - save_cache:
          key: my-special-file-{{ .Environment.CACHE_PR_KEY }}
          paths:
            - ./packages
      - run: |
          echo "Hello Hola"
           
workflows:
  La-Build:
    jobs:
    - show-pr-refs
