version: 2.1

jobs:
  job-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   git clone --branch master --single-branch --depth 1 https://github.com/XkuzemyFrench/restore-cache.git .
                   git fetch --depth=1 --force origin "master:remotes/origin/master"
                   git checkout -q -B master
                   
workflows:

  whodidthis:
    jobs:
      - job-1
