version: 2.1

parameters:
  further:
    type: boolean
    default: true
  cucumber-options:
    type: string
    default: "--tags @check"
  billbool:
    type: boolean
    default: true

jobs:
  lejob:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          echo << pipeline.parameters.further >>
          echo << pipeline.parameters.cucumber-options >>
          echo << pipeline.parameters.billbool >>
          echo "Hello, I'm continuing"

workflows:
  setup-workflow:
#     when: << pipeline.parameters.further >>
    jobs:
      - lejob
