version: 2.1

jobs:
  my_job:
    docker:
      - image: cimg/base:2023.02
    steps:
      - run: |
          echo "<< pipeline.id >>"
          echo "<< pipeline.project.git_url >>"
          echo 'pipeline.git.revision=<<pipeline.git.revision>>' > rev.txt
          cat rev.txt
#       - checkout
#       - my-orb/my_command

workflows:
  main:
    jobs:
      - my_job
