version: 2.1

parameters:
  further:
    type: boolean
    default: true
#   run-path-a:
#     type: boolean
#     default: false
#   run-path-b:
#     type: boolean
#     default: false

jobs:
  lejob:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sleep 15
          echo "Hello, I'm continuing"

workflows:
  setup-workflow:
    when: << pipeline.parameters.further >>
    jobs:
      - lejob
