version: 2.1

jobs:
  lejob:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          sleep 12
          echo "Hello, I'm continuing"

workflows:
  setup-workflow:
    jobs:
      - lejob
